[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-UA-Compatible = "IE=edge"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
